### ISSUE TITLE
使用github存放图片资源专贴

### ISSUE THREAD

**Issue by nimojs** [nimojs/blog#10]
![image](https://cloud.githubusercontent.com/assets/3949015/6520889/dd3df26c-c408-11e4-8758-1f9aa86f9439.png)

**Comment by nimojs** [comment]
![aa](https://cloud.githubusercontent.com/assets/3949015/6521883/eefc0458-c417-11e4-9134-7d2fd442e4f6.gif)

**Comment by nimojs** [comment]
![image](https://cloud.githubusercontent.com/assets/3949015/7514594/6a6dea84-f4f1-11e4-9530-1f89eed33c29.png)

**Comment by nimojs** [comment]
![image](https://cloud.githubusercontent.com/assets/3949015/9734280/48ffc532-5664-11e5-9d1e-21f1b412bcbf.png)

**Comment by crrlxx** [comment]
![test](https://cloud.githubusercontent.com/assets/17776175/17547667/fd08e864-5f1a-11e6-8c22-fca7356b4494.png)

**Comment by nimojs** [comment]
![image](https://user-images.githubusercontent.com/3949015/44773517-622dfc80-aba3-11e8-8bc5-0a06a58c449e.png)
