### ISSUE TITLE
使用淘宝NPM镜像

### ISSUE THREAD

**Issue by nimojs** [nimojs/blog#20]
使用淘宝NPM镜像
===============

本文是 [《Gulp 入门指南》 - 安装 Node 和 gulp](https://github.com/nimojs/gulp-book/blob/master/chapter1.md) 的附属教程

> 在使用 node 模块时可以使用 `npm install` 查找 [package.json](https://github.com/nimojs/gulp-demo/blob/master/package.json) 中的声明的依赖模块并安装。

但因为国内网络原因，使用 npm 安装某些模块会非常慢。

例如 [gulp-demo](https://github.com/nimojs/gulp-demo/blob/master/package.json) 依赖了十多个模块，使用 `npm install` 时经常因为网络原因无法安装所有的包。

---------

好在淘宝提供了 npm 镜像供我们使用。
## 安装 cnpm
在命令行输入：
```
npm install -g cnpm --registry=https://registry.npm.taobao.org
```

## 使用 cnpm 安装模块

```
cnpm install [name]
```

> 这真的是个大坑，有时候一个 基于 gulp 的自动化开发环境的依赖包文件会有几十MB。使用 npm 安装很久也不一定能安装完成。

**相关链接：**

- [gulp 入门指南](https://github.com/nimojs/gulp-book)

[点此订阅博客](https://github.com/nimojs/blog/issues/15)

若作者显示不是Nimo（被转载了），请访问Github原文进行讨论：[https://github.com/nimojs/blog/issues/20](https://github.com/nimojs/blog/issues/20)

**Comment by huanmie913** [comment]
感谢楼主无私分享

**Comment by leo-lai** [comment]
cnpm install -g [name] 全局安装是用这个么？

**Comment by nimojs** [comment]
@leo-lai  是的 cnpm 命令基本与 npm 一致。但没有 publish 功能。

**Comment by leo-lai** [comment]
@nimojs 知道了，非常感谢您的回复

**Comment by ehazon** [comment]
**感谢,用 gulp 的时候 npm 原生太慢**

**Comment by Lyzh** [comment]
感谢楼主分享。学习了

**Comment by Aisuko** [comment]
感谢楼主无私分享，Get

**Comment by Kevin-Gallagher** [comment]
为什么我照你说的方法安装了，命令行输入gulp -v还是说“gulp”不是外部或内部命令，也不是可运行的程序或批处理文件？

**Comment by nimojs** [comment]
@Kevin-Gallagher 
试试在C盘运行，然后是通过 `npm install -g gulp` 安装的吗

**Comment by happyyangyuan** [comment]
中间还有一步是 node-pre-gyp http GET https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v48-linux-x64.tar.gz
还是失败
