### ISSUE TITLE
利用 Github contributions 进行 259 天时间管理挑战

### ISSUE THREAD

**Issue by nimojs** [nimojs/blog#27]
**现状：**
1. 最爱 github 和开源
2. 有不少有价值的开源项目值得维护和创建（数据模拟、node工具、前端组件、前端教程规范）
3. 大段代码直接 push, commit 信息不详细
4. 代码提交不稳定（时有时无）

**计划：**
1. 2016-04-17 ~ 2017-01-01 保存每天 commit 
2. commit message 不随意
3. 每天最少30分钟贡献给开源项目
4. 阶段性在此 issues 总结（月初：一月一次）
5. 每个项目必须有单元测试、API文档、示例代码、releases 记录

**为什么要这么做？**
1. 学会管理时间，强迫自己不停的贡献高质量开源项目
2. 利用开源项目解决工作中会遇到的问题和沉淀经验
3. 强制自己每天写高质量代码提高自己
4. 将前端技能树的各个分支在 github 体现出来（程序员的自我营销）
## 日志

> 2016年04月17日00:17:04

![111](https://cloud.githubusercontent.com/assets/3949015/14582394/1753ade8-0436-11e6-999c-7df6352853ec.gif)

发布 [markrun](https://github.com/nimojs/markrun) 0.0.1

![](https://pic1.zhimg.com/v2-ea850cadc6394ef56b2ca5b3d634654e.png)

**Comment by yunshuipiao** [comment]
值得学习，我也打算把博客写到这里。请问收货大吗？

**Comment by wangjiangithub** [comment]
怎么在github写博客，申请博客空间

**Comment by yunshuipiao** [comment]
其实写在这就挺好的，不用太麻烦

**Comment by nimojs** [comment]
@yunshuipiao github写博客的好处是不用折腾服务器和博客主题，且github社区成员质量高。

**Comment by nimojs** [comment]
@wangjiangithub 比如你建一个项目 `wangjiangithub.github.io`

然后打开 https://github.com/wangjiangithub/wangjiangithub.github.io/settings

 GitHub Pages 选项中选择 `master branch` 访问 http://wangjiangithub.github.io/ 会访问 wangjiangithub.github.io 项目下对应的文件。
初期在  issues 里面写就可以了。

**Comment by yunshuipiao** [comment]
@nimojs 
你说的博客我倒是有弄过，用hexo，好像是。
感觉不错，但和issues下面谁优谁劣我就不是很清楚了.
能说一下你的看法吗

**Comment by nimojs** [comment]
从最初的 wordpress，到博客园，到 github pages jekyll hexo，这些我都尝试过。最终发现技术人员最好是在 github.

**优点**
1. 0配置
2. markdown语法支持良好
3. issues 能有效社交

**比较**
1. WordPress因为是个人站，所以流量会很少，就会很少有人留言讨论。
2. WordPress的主题可以很漂亮
3. 博客园会有不少人讨论，但是github社区成员质量高
4. issues 界面不可以修改，会有人乱开 issues
5. issues 中可以与github任何项目的代码管理
6. hexo 这种类型的 github blog，除非文章很牛X，否则别人还是不习惯访问。

最终我不想折腾了，就用 issues 了，而且还可以集Star哦 。集齐1000个可召唤神龙。

我再安利一发：

http://nimojs.github.io/github-comments/

> 让评论质量更高，让网站与 Github 关联
> 适合程序员的评论系统，基于 Github issues 留言

[![preview](https://cloud.githubusercontent.com/assets/3949015/11060115/1892a24c-87d9-11e5-80a0-651c60f90875.png)](http://nimojs.github.io/github-comments/)

使用 github-comments 挂到自己的网站后，可以显示指定 issues 的回复，互动就更多了。

**Comment by yunshuipiao** [comment]
@nimojs 
这个安利我吃，非常感谢这么详细的讲解。
马上去试试这个评论

**Comment by nimojs** [comment]
https://github.com/markrun/markrun
https://github.com/fast-flow/react
https://github.com/fast-flow/admin
https://github.com/fast-flow
